language: node_js
node_js:
  # Select a Node version where there is a Fibers binary available.
  - 12.22.12
branches:
  only:
    - master
cache:
  directories:
  - node_modules/
script:
  - npm run lint
  - npm run test
